2019-12-03 09:24:35,324 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:(lineno)d]
2019-12-03 09:24:59,938 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:47]
2019-12-03 10:24:02,723 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-03 10:24:08,069 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-04 17:08:38,382 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-04 17:09:35,079 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-04 17:09:52,344 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-04 17:10:24,354 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-05 10:11:34,753 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-05 10:12:19,607 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-05 10:13:49,333 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-05 10:59:57,255 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
2019-12-05 11:00:06,630 ERROR: Exception on /login [GET] [in /Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/scammons/Projects/learn_flask/app/routes.py", line 52, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/scammons/Projects/learn_flask/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/scammons/Projects/learn_flask/app/templates/login.html", line 14, in root
    <p>
  File "/Users/scammons/Projects/learn_flask/app/templates/base.html", line 25, in root
    {% endfor %}
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'epxlore'. Did you mean 'explore' instead?
2019-12-05 11:01:07,932 ERROR: Exception on /login [GET] [in /Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/scammons/Projects/learn_flask/app/routes.py", line 52, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/scammons/Projects/learn_flask/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/scammons/Projects/learn_flask/app/templates/login.html", line 14, in root
    <p>
  File "/Users/scammons/Projects/learn_flask/app/templates/base.html", line 25, in root
    {% endfor %}
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/scammons/Projects/learn_flask/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'epxlore'. Did you mean 'explore' instead?
2019-12-05 11:01:11,049 INFO: Microblog startup [in /Users/scammons/Projects/learn_flask/app/__init__.py:48]
